#Validate #.gitlab-ci.yml at https://git.statoil.no/ci/lint
stages:
  - build
#  - test
  - publish
#  - clean
  - deploy

variables:
  API_IMAGE: $CI_REGISTRY/volumetric/api
  WEB_IMAGE: $CI_REGISTRY/volumetric/web
  #FULL_API_IMAGE: $CI_REGISTRY/$API_IMAGE
  #FULL_WEB_IMAGE: $CI_REGISTRY/$WEB_IMAGE_NAME
  IMAGE_TAG: $CI_COMMIT_REF_NAME
  PROJECT_PATH: /data/vlmtrc
  MAIN_PATH: $PROJECT_PATH/main
  API_PATH: $PROJECT_PATH/api
  WEB_PATH: $PROJECT_PATH/web


#before_script:
#- /bin/activate
#- /bin/clone-repos

#build_api:
#  stage: build
#  script:
#    - docker build -t $API_IMAGE ./app
#build_web:
#  stage: build
#  script:
#    - docker build -t $WEB_IMAGE ./web

#publish_images:
#  stage: publish
#  before_script:
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#  script:
#    - docker tag $API_IMAGE $FULL_API_IMAGE:$IMAGE_TAG
#    - docker tag $WEB_IMAGE_NAME $FULL_WEB_IMAGE:$IMAGE_TAG
#    - docker push $FULL_API_IMAGE:$IMAGE_TAG
#    - docker push $FULL_WEB_IMAGE:$IMAGE_TAG

deploy_develop:
  stage: deploy
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker-compose -f $MAIN_PATH/docker-compose.yml up -d

