#Validate .gitlab-ci.yml at https://git.statoil.no/ci/lint
stages:
  - build
  - publish
  - document
  - deploy

variables:
  API_IMAGE: $CI_REGISTRY/volumetric/api
  API_PATH: /data/vlmtrc/api

build_api:
  stage: build
  script:
    - docker build --force-rm -t $API_IMAGE .
    - docker tag $API_IMAGE $API_IMAGE:$CI_COMMIT_REF_NAME

publish_image:
  stage: publish
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push $API_IMAGE
    - docker push $API_IMAGE:$CI_COMMIT_REF_NAME

create_erd:
  stage: document
  variables:
    COMPOSE_PROJECT_NAME: api$CI_JOB_ID
  before_script:
    - docker network create vlmtrc-ci-net
    - docker-compose -f docker-compose.ci.yml run --rm api manage db upgrade
    - mkdir -p data/build
  script:
    - docker run --rm -v "$PWD/data/build:/share" --net vlmtrc-ci-net --name schemacrawler --user $(id -u) --entrypoint /opt/schemacrawler/schemacrawler.sh schemacrawler/schemacrawler -server=postgresql -host=db -user=volumetric -password=$POSTGRES_PASSWORD -database=volumetric -infolevel=standard -routines -command=schema -outputformat=png -o /share/schema.png
  after_script:
    - docker-compose -f docker-compose.ci.yml down
    - docker network rm vlmtrc-ci-net
  artifacts:
    paths:
      - data/build/
    expire_in: 1 week

deploy_develop:
  stage: deploy
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" > $API_PATH/secrets.env
    - echo "FLASK_SECRET_KEY=$FLASK_SECRET_KEY" >> $API_PATH/secrets.env
    - cp docker-compose.yml $API_PATH/
  script:
    - docker-compose --compatibility -f $API_PATH/docker-compose.yml run api manage import_test --test_file='TestData_all.txt'
    - docker-compose --compatibility -f $API_PATH/docker-compose.yml up -d

# Might add something like this so volumetric/main pipeline gets triggered by a successful api pipeline
#trigger_build:
 # stage: deploy
  #script:
   # - "curl -X POST -F token=TOKEN -F ref=REF_NAME https://git.statoil.no/api/v4/projects/1860/trigger/pipeline"
