#Validate .gitlab-ci.yml at https://git.statoil.no/ci/lint
stages:
  - build
  - tests
  - publish
  - deploy

variables:
  PUBLISH_IMAGE: $CI_REGISTRY/volumetric/web
  BUILD_IMAGE: $CI_REGISTRY/volumetric/web:$CI_PIPELINE_ID
  PROJECT_PATH: /data/vlmtrc

build_web:
  stage: build
  script:
    - docker build -t $BUILD_IMAGE .

test:
  stage: tests
  script:
    - WEB_IMAGE=$BUILD_IMAGE docker-compose -f docker-compose.ci.yml run --rm -e CI=true web yarn test

audit:
  stage: tests
  script:
    - WEB_IMAGE=$BUILD_IMAGE docker-compose -f docker-compose.ci.yml run --rm web yarn audit
  allow_failure: true

format:
  stage: tests
  script:
    - WEB_IMAGE=$BUILD_IMAGE docker-compose -f docker-compose.ci.yml run --rm web prettier --single-quote --trailing-comma all --list-different "{,*/**/}*.js" "!build/**/*.js" "!node_modules/**/*.js"

publish_image:
  stage: publish
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker tag $BUILD_IMAGE $PUBLISH_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $PUBLISH_IMAGE:$CI_COMMIT_REF_SLUG

deploy_develop:
  stage: deploy
  tags:
    - dev
  only:
    - master
  environment:
    name: development
    url: http://dev.volumetric.equinor.com
  variables:
    ENVIRONMENT: "dev"
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - sed -i "/^ENVIRONMENT=.*/c\ENVIRONMENT=$ENVIRONMENT" $PROJECT_PATH/main/release
  script:
    - cd $PROJECT_PATH/main
    - git pull
    - ./bin/activate volumetric pull
    - ./bin/activate volumetric build proxy
    - ./bin/activate volumetric up -d --scale worker=3


deploy_test:
  stage: deploy
  tags:
    - test
  only:
    - /^v.*$/
  except:
    - branches
  environment:
    name: test
    url: http://test.volumetric.equinor.com
  variables:
    ENVIRONMENT: "test"
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - sed -i "/^WEB_TAG=.*/c\WEB_TAG=$CI_COMMIT_REF_NAME" $PROJECT_PATH/main/.env
    - sed -i "/^ENVIRONMENT=.*/c\ENVIRONMENT=$ENVIRONMENT" $PROJECT_PATH/main/.env
  script:
    - cd $PROJECT_PATH/main
    - git pull
    - ./bin/activate volumetric pull
    - ./bin/activate volumetric build proxy
    - ./bin/activate volumetric up -d --scale worker=3
