#Validate .gitlab-ci.yml at https://git.statoil.no/ci/lint
stages:
  - build
  - publish
  - deploy

variables:
  API_IMAGE: $CI_REGISTRY/volumetric/api
  API_PATH: /data/vlmtrc/api

build_api:
  stage: build
  before_script:
  script:
    - docker build --force-rm -t $API_IMAGE .
    - docker tag $API_IMAGE $API_IMAGE:$CI_COMMIT_REF_NAME

publish_image:
  stage: publish
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push $API_IMAGE
    - docker push $API_IMAGE:$CI_COMMIT_REF_NAME

deploy_develop:
  stage: deploy
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" > $API_PATH/secrets.env
    - echo "FLASK_SECRET_KEY=$FLASK_SECRET_KEY" >> $API_PATH/secrets.env
    - cp docker-compose.yml $API_PATH/
  script:
    - docker-compose --compatibility -f $API_PATH/docker-compose.yml up -d

# Might add something like this so volumetric/main pipeline gets triggered by a successful api pipeline
#trigger_build:
 # stage: deploy
  #script:
   # - "curl -X POST -F token=TOKEN -F ref=REF_NAME https://git.statoil.no/api/v4/projects/1860/trigger/pipeline"
