version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - web
      - api

  web:
    image: git.statoil.no:4567/volumetric/web

  api:
    image: git.statoil.no:4567/volumetric/api
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric

  db:
    image: postgres:10.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./../api/data/postgres:/var/lib/postgres
      - ./../api/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
