version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - web
      - api
    restart: unless-stopped

  web:
    image: git.statoil.no:4567/volumetric/web
    command: serve -s build
    env_file:
      - secrets.env
    restart: unless-stopped

  api:
    image: git.statoil.no:4567/volumetric/api
    depends_on:
      - db
    env_file:
      - secrets.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
    restart: unless-stopped

  db:
    image: postgres:10.2-alpine
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - secrets.env
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
    restart: unless-stopped
