version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - api
    environment:
      - TZ=Europe/Oslo

  web:
    image: git.equinor.com:4567/volumetric/volumetric/web
    restart: unless-stopped
    command: serve --single build --listen 3000

  api:
    image: git.equinor.com:4567/volumetric/volumetric/api
    depends_on:
      - redis
      - worker
    environment:
      - ENVIRONMENT=local
      - REDIS_HOST=redis
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - AZURE_APP_CLIENT_ID=c049f236-7e38-41ba-be77-287bc1c8543c
      - AZURE_KEYS_URI=https://login.microsoftonline.com/common/discovery/v2.0/keys
      - AZURE_FILES_ACCOUNT=${POSTGRES_PASSWORD}
      - AZURE_FILES_KEY=${AZURE_FILES_KEY}

  redis:
    build:
      context: redis
    command: ["--tcp-backlog", "128"]

  worker:
    image: git.equinor.com:4567/volumetric/volumetric/api
    command: ["worker"]
    environment:
      - ENVIRONMENT=local
      - REDIS_HOST=redis
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - AZURE_APP_CLIENT_ID=c049f236-7e38-41ba-be77-287bc1c8543c
      - AZURE_KEYS_URI=https://login.microsoftonline.com/common/discovery/v2.0/keys
      - AZURE_FILES_ACCOUNT=${POSTGRES_PASSWORD}
      - AZURE_FILES_KEY=${AZURE_FILES_KEY}
