version: "3.6"
services:

  api:
    image: vlmtrc-api
    container_name: volumetric-api
    ports:
      - "80:80"
      # For live debugging
    volumes:
      - .:/src
    env_file: secrets.env
    environment:
      - PORT=80
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: postgres:10.2-alpine
    container_name: volumetric-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgres
    env_file: secrets.env
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
    restart: unless-stopped
