version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - web
      - api

  web:
    image: git.statoil.no:4567/volumetric/web:$WEB_TAG
    env_file:
      - secrets.env

  api:
    image: git.statoil.no:4567/volumetric/api:$API_TAG
    depends_on:
      - db
    env_file:
      - secrets.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric

  db:
    image: postgres:10.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    env_file:
      - secrets.env
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
