version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - web
      - api

  web:
    build:
      context: ../web
      args:
        UID: $DOCKER_USER
        GID: $DOCKER_GROUP
    image: git.statoil.no:4567/volumetric/web
    volumes:
      - ./../web/src:/code/src
      - ./../web/public:/code/public

  api:
    image: git.statoil.no:4567/volumetric/api
    container_name: volumetric-api
    build: ../api
    env_file: ./../api/secrets.env
    volumes:
      - ./../api:/code
    depends_on:
      - db
    environment:
      - API_PORT=80
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric

  db:
    image: postgres:10.2-alpine
    command: postgres -c 'log_statement=mod'
    container_name: volumetric-db
    ports:
      - "5432:5432"
    volumes:
      - ./../api/data/postgres:/var/lib/postgres
    env_file: ./../api/secrets.env
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
