version: "2.4"
services:

  api:
    image: git.statoil.no:4567/volumetric/api:master
    container_name: volumetric-api
    ports:
      - "80:8080"
    env_file: secrets.env
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
      - FLASK_ENV=production
    depends_on:
      - postgresql

  postgresql:
    image: postgres:10.2-alpine
    container_name: volumetric-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgres
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    env_file: secrets.env
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
