version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - web
      - api
    restart: unless-stopped

  web:
    image: git.equinor.com:4567/volumetric/web:master
    command: serve -s build
    env_file:
      - secrets.env
    restart: unless-stopped

  api:
    image: git.equinor.com:4567/volumetric/api:master
    depends_on:
      - db
    env_file:
      - secrets.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
      - AZURE_APP_CLIENT_ID=c049f236-7e38-41ba-be77-287bc1c8543c
      - AZURE_KEYS_URI=https://login.microsoftonline.com/common/discovery/v2.0/keysA
    restart: on-failure

  db:
    image: postgres:10.2-alpine
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - secrets.env
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
    restart: unless-stopped
