version: '3.4'

services:
  proxy:
    build: proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
    - ./proxy/x.volumetric.equinor.com.key:/etc/nginx/ssl/x.volumetric.equinor.com.key

  web:
    image: git.equinor.com:4567/volumetric/web:$WEB_TAG
    command: serve --single build --listen 3000
    env_file:
      - secrets.env
    restart: unless-stopped

  api:
    image: git.equinor.com:4567/volumetric/api:$API_TAG
    depends_on:
      - redis
      - worker
    env_file:
      - secrets.env
    environment:
      - ENVIRONMENT=test
      - REDIS_HOST=redis
      - DATABASE_HOST=volumetric-prod.postgres.database.azure.com
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric@volumetric-prod
      - POSTGRES_DB=volumetric
      - AZURE_APP_CLIENT_ID=c049f236-7e38-41ba-be77-287bc1c8543c
      - AZURE_KEYS_URI=https://login.microsoftonline.com/common/discovery/v2.0/keys
    restart: unless-stopped

  redis:
    image: redis:5.0-alpine
    restart: unless-stopped

  worker:
    image: git.equinor.com:4567/volumetric/api:$API_TAG
    command: ["worker"]
    env_file:
    - secrets.env
    environment:
    - ENVIRONMENT=test
    - REDIS_HOST=redis
    - DATABASE_HOST=volumetric-prod.postgres.database.azure.com
    - DATABASE_PORT=5432
    - POSTGRES_USER=volumetric@volumetric-prod
    - POSTGRES_DB=volumetric
    - FLASK_ENV=development
    - AZURE_APP_CLIENT_ID=c049f236-7e38-41ba-be77-287bc1c8543c
    - AZURE_KEYS_URI=https://login.microsoftonline.com/common/discovery/v2.0/keys
    restart: unless-stopped
