"""initial_schema

Revision ID: f18d7633ec93
Revises: 
Create Date: 2018-04-25 11:39:22.321272

"""
from alembic import op, context
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f18d7633ec93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'metrics', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('realization', sa.Integer(), nullable=True),
        sa.Column('faultblock', sa.String(), nullable=True),
        sa.Column('zone', sa.String(), nullable=True),
        sa.Column('grv', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('nrv', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('npv', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('hcpv', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('stoiip', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
