"""initial_db

Revision ID: f9c586cf8fd4
Revises: 
Create Date: 2018-08-01 08:47:49.991654

"""
from alembic import op, context
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f9c586cf8fd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field', sa.Column('name', sa.String(), nullable=False), sa.PrimaryKeyConstraint('name'),
                    sa.UniqueConstraint('name'))
    op.create_table('model', sa.Column('name', sa.String(), nullable=False),
                    sa.Column('user', sa.String(), nullable=True), sa.Column('field_name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['field_name'], ['field.name'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('name'), sa.UniqueConstraint('name', 'user'))
    op.create_table('location', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('model_name', sa.String(), nullable=False),
                    sa.Column('faultblock_name', sa.String(), nullable=True),
                    sa.Column('zone_name', sa.String(), nullable=True),
                    sa.Column('facies_name', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['model_name'], ['model.name'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('faultblock_name', 'zone_name', 'facies_name'))
    op.create_table('volumetrics', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('realization', sa.Integer(), nullable=True),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('grv', sa.Numeric(precision=20, scale=2), nullable=True),
                    sa.Column('nrv', sa.Numeric(precision=20, scale=2), nullable=True),
                    sa.Column('npv', sa.Numeric(precision=20, scale=2), nullable=True),
                    sa.Column('hcpv', sa.Numeric(precision=20, scale=2), nullable=True),
                    sa.Column('stoiip', sa.Numeric(precision=20, scale=2), nullable=True),
                    sa.ForeignKeyConstraint(['location_id'], ['location.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('realization', 'location_id'))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volumetrics')
    op.drop_table('location')
    op.drop_table('model')
    op.drop_table('field')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
