"""add_metrics_and_phases_to_case

Revision ID: 828d58d2e6c2
Revises: 06f7946ad1e7
Create Date: 2019-04-12 09:10:24.624963

"""
from alembic import op, context
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '828d58d2e6c2'
down_revision = '06f7946ad1e7'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('metrics', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('case', sa.Column('phases', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'phases')
    op.drop_column('case', 'metrics')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
