"""add_shared_case

Revision ID: 874b5d752386
Revises: 8d883d840600
Create Date: 2019-05-23 13:34:34.743687

"""
from alembic import op, context
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import table, Column, Integer, Boolean

revision = '874b5d752386'
down_revision = '8d883d840600'
branch_labels = None
depends_on = None

case_table = table(
    'case',
    Column('id', Integer, primary_key=True),
    Column('is_official', Boolean),
    Column('is_shared', Boolean),
)


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data') == 'true':
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('is_shared', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'is_shared')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    op.execute(case_table.update().where(case_table.c.is_official).values(is_shared=True))


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
