version: "3"

networks:
  ci:
    external:
      name: vlmtrc-ci-net-$CI_JOB_ID

services:
  api:
    image: $BUILD_IMAGE_API
    networks:
      - ci
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - ENVIRONMENT=CI
    depends_on:
      - db

  db:
    image: postgres:10.2-alpine
    networks:
      - ci
    environment:
      - POSTGRES_USER=volumetric
      - POSTGRES_DB=volumetric
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
